server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations:
            #- "classpath:/config"
            #- "file:///Users//eazybytes//Documents//config"
        git:
          uri: "https://github.com/Atanu1081/config-server.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true